allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        ivy {
            url 'https://github.com/edgez-ai/organicmaps/releases/download/v0.0.4'
            patternLayout {
                artifact '[artifact]-[revision].[ext]'
            }
            metadataSources {
                artifact()
            }
            content {
                includeGroup 'ai.edgez.organicmaps'
            }
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
