// Generated by .github/workflows/release.yml. Do not edit.
const String edgezSdkCompatibility = "^0.5.0";
const String edgezSdkReleaseId = "edgez_flutter_sdk@0.1.0";
const String edgezSdkReleaseSignatureHex = "0BEEE33C5291FEE11B66939E7641B490BA2CB307C394D905B15D7A08933D91DD141EC96081EDB5D1815A49B1C5D64EC774DEE9B4C67F2C935A84ABCB68ACA98B";
