// Generated by .github/workflows/release.yml. Do not edit.
const String edgezSdkCompatibility = "^0.5.0";
const String edgezSdkReleaseId = "edgez_flutter_sdk@0.4.0";
const String edgezSdkReleaseSignatureHex = "B392DD0E97EF64F64AEE92AB0FAB29480474D687F8A5F90B8A86BB94A30E3C50DC4EB1EA1ADC5403B61DC138B5212B9C6E7453CA262300AA05E288BAB25E006C";
