// Generated by .github/workflows/release.yml. Do not edit.
const String edgezSdkCompatibility = "^0.5.0";
const String edgezSdkReleaseId = "edgez_flutter_sdk@0.1.0";
const String edgezSdkReleaseSignatureHex = "";
